// Estructura del tablero: columnas (pasos) y flechas (condiciones).
// ─── Qué va en cada columna, y en qué orden ─────────────────────────────────
export const COLUMNAS = [
  { nombre: 'Entrada', ids: ['00-landing', '00b-landing-pedido-reciente', '00c-landing-pago-pendiente'] },
  { nombre: 'Paso 1 · Tu pack', ids: ['01-paso1-pack', '01b-paso1-descuento-aplicado'] },
  { nombre: 'Paso 2 · Tus datos', ids: ['02-paso2-inicial', '02b-paso2-dni-validando', '02c-paso2-dni-validado', '02d-paso2-dni-no-validado', '02e-paso2-errores', '02f-paso2-distrito-buscando'] },
  { nombre: 'Rama Lima (Lima Metro y Callao)', ids: ['03-lima-A-domicilio', '03b-lima-B-elegir', '03c-lima-B-casa', '03d-lima-agencia-cercanas', '03e-lima-agencia-buscar', '03f-lima-sin-domicilio'] },
  { nombre: 'Rama Provincia', ids: ['04-prov-A-domicilio', '04b-prov-A-agencia-elegida', '04c-prov-sin-cobertura', '04d-prov-semanal', '04e-prov-B-elegir', '04f-prov-B-casa', '04g-prov-B-agencia', '04i-prov-B-volver', '04h-prov-adelanto-mitad'] },
  { nombre: 'Paso 3 · Confirmar', ids: ['05-paso3-total-domicilio', '05i-paso3-registrando', '05h-paso3-error-registro', '05b-paso3-total-agencia', '05c-paso3-mitad-opciones', '05d-paso3-mitad-elegida', '05e-paso3-mitad-agencia', '05g-paso3-nota-zona', '05f-paso3-sin-cobro-en-linea'] },
  { nombre: 'Pago (Flow · Yape)', ids: ['07-pago-emitiendo', '07c-pago-yape', '07b-pago-esperando-al-volver', '07d-pago-fallo'] },
  { nombre: 'Pedido confirmado · /pedido/:token', ids: ['08-pedido-confirmado-domicilio', '08b-pedido-confirmado-agencia-saldo', '08c-pedido-pago-pendiente', '08d-pedido-coordinar-por-chat', '08e-pedido-confirmado-iphone'] },
  { nombre: 'Salida (X / Esc)', ids: ['06-salida-oferta', '06b-salida-confirmar'] },
]

// ─── Las flechas: de dónde a dónde, y con qué condición ─────────────────────
// tipo: 'avanza' (sólida) · 'vuelve' (discontinua) · 'variante' (punteada, misma pantalla en otra condición)
export const FLECHAS = [
  ['00-landing', '01-paso1-pack', '«¡Lo quiero!» abre el checkout (bottom-sheet)'],
  ['01-paso1-pack', '02-paso2-inicial', '«Continuar» (el CTA nunca se bloquea en el paso 1)'],
  ['02-paso2-inicial', '02b-paso2-dni-validando', 'DNI de 8 dígitos → consulta a RENIEC'],
  ['02b-paso2-dni-validando', '02c-paso2-dni-validado', 'RENIEC devolvió nombre → rellena «quien recibe»'],
  ['02b-paso2-dni-validando', '02d-paso2-dni-no-validado', 'No encontrado o servicio caído → sigue igual'],
  ['02c-paso2-dni-validado', '02f-paso2-distrito-buscando', 'Toca «¿A qué distrito enviamos?» y escribe'],
  ['02c-paso2-dni-validado', '02e-paso2-errores', 'Toca «Continuar» con campos inválidos (o los deja vacíos al salir de ellos)'],
  ['02f-paso2-distrito-buscando', '03-lima-A-domicilio', 'Distrito de Lima Metro/Callao · la marca reparte · variante A → DOMICILIO fijado solo'],
  ['02f-paso2-distrito-buscando', '03b-lima-B-elegir', 'Lima · la marca reparte · variante B → elige el comprador'],
  ['02f-paso2-distrito-buscando', '03f-lima-sin-domicilio', 'Lima · home_delivery_enabled = false y sin courier → AGENCIA forzada'],
  ['03b-lima-B-elegir', '03c-lima-B-casa', '«En mi casa»'],
  ['03b-lima-B-elegir', '03d-lima-agencia-cercanas', '«Recojo en agencia»'],
  ['03d-lima-agencia-cercanas', '03e-lima-agencia-buscar', '«Ver todos los puntos de mi zona»'],
  ['02f-paso2-distrito-buscando', '04-prov-A-domicilio', 'Provincia · cobertura IN_ZONE · variante A → DOMICILIO'],
  ['02f-paso2-distrito-buscando', '04c-prov-sin-cobertura', 'Provincia · OUT_OF_ZONE (o la marca no reparte) → AGENCIA'],
  ['02f-paso2-distrito-buscando', '04d-prov-semanal', 'Provincia · zona de visita semanal → BORDERLINE → AGENCIA + aviso'],
  ['02f-paso2-distrito-buscando', '04e-prov-B-elegir', 'Provincia · IN_ZONE · variante B → elige el comprador'],
  ['04-prov-A-domicilio', '04b-prov-A-agencia-elegida', '«Prefiero recoger en una agencia»'],
  ['04b-prov-A-agencia-elegida', '04-prov-A-domicilio', '«Prefiero intentar entrega a domicilio» (solo con IN_ZONE)', 'vuelve'],
  ['04e-prov-B-elegir', '04f-prov-B-casa', '«En mi casa»'],
  ['04e-prov-B-elegir', '04g-prov-B-agencia', '«Recojo en agencia»'],
  ['05d-paso3-mitad-elegida', '04i-prov-B-volver', '«Atrás» en variante B: se re-consulta la cobertura y el método queda en blanco', 'vuelve'],
  ['04i-prov-B-volver', '04h-prov-adelanto-mitad', 'Re-elige «En mi casa» con la mitad ya elegida'],
  ['03-lima-A-domicilio', '05-paso3-total-domicilio', '«Continuar» · domicilio · paga todo · Flow activo'],
  ['03d-lima-agencia-cercanas', '05b-paso3-total-agencia', '«Continuar» · recojo en agencia (también desde 03f, 04b, 04c, 04d)'],
  ['04f-prov-B-casa', '05c-paso3-mitad-opciones', '«Continuar» · products.permite_mitad = true → aparece el reparto'],
  ['04g-prov-B-agencia', '05e-paso3-mitad-agencia', '«Continuar» · agencia + permite_mitad → «Pago la mitad ahora»'],
  ['04-prov-A-domicilio', '05g-paso3-nota-zona', '«Continuar» · distrito con entrega solo L–V (weekdaysOnly) → nota ámbar'],
  ['05c-paso3-mitad-opciones', '05d-paso3-mitad-elegida', '«Pago la mitad ahora» (domicilio)'],
  ['05-paso3-total-domicilio', '05f-paso3-sin-cobro-en-linea', 'Variante: stores.flow_enabled = false → aviso «lo coordinamos por el chat»', 'variante'],
  ['05-paso3-total-domicilio', '05i-paso3-registrando', '«Terminar mi pedido» → register-buyer (idempotente por checkout_id)'],
  ['05i-paso3-registrando', '05h-paso3-error-registro', 'register-buyer falla → error y reintento sin perder datos'],
  ['05i-paso3-registrando', '07-pago-emitiendo', 'Registro OK · riel FLOW (lo decide el servidor) → flow-order'],
  ['05f-paso3-sin-cobro-en-linea', '08d-pedido-coordinar-por-chat', '«Terminar mi pedido» · sin riel → REGISTERED_MANUAL → /pedido/:token'],
  ['07-pago-emitiendo', '07c-pago-yape', 'Celular + el servidor sacó el deeplink de Yape → AWAITING'],
  ['07-pago-emitiendo', '07b-pago-esperando-al-volver', 'Sin deeplink (o escritorio): sale a la página de Flow; al volver, espera'],
  ['07-pago-emitiendo', '07d-pago-fallo', 'flow-order falla → ISSUE_FAILED'],
  ['07d-pago-fallo', '07-pago-emitiendo', '«Reintentar el pago» (solo desde ISSUE_FAILED)', 'vuelve'],
  ['07c-pago-yape', '08-pedido-confirmado-domicilio', 'El webhook cruza el pago (MATCHED) → navega a /pedido/:token'],
  ['07b-pago-esperando-al-volver', '08-pedido-confirmado-domicilio', 'MATCHED visto por el sondeo cada 3 s'],
  ['07d-pago-fallo', '08c-pedido-pago-pendiente', '«Prefiero que me escriban para pagar» (GIVE_UP)'],
  ['08-pedido-confirmado-domicilio', '08b-pedido-confirmado-agencia-saldo', 'Variante: pagó la mitad + recojo en agencia (saldo por la app, DNI, clave)', 'variante'],
  ['08-pedido-confirmado-domicilio', '08e-pedido-confirmado-iphone', 'Variante: iPhone (sin push web → video de instalación)', 'variante'],
  ['08-pedido-confirmado-domicilio', '00b-landing-pedido-reciente', 'Vuelve a la landing con el pedido guardado (24 h)', 'vuelve'],
  ['07d-pago-fallo', '00c-landing-pago-pendiente', 'Cierra el modal con el pago a medias (advancePending)', 'vuelve'],
  ['03-lima-A-domicilio', '06-salida-oferta', 'X o Esc con datos ingresados · descuento_pen > 0 · aún no ofrecido (desde cualquier paso)'],
  ['06-salida-oferta', '06b-salida-confirmar', 'Segundo intento de salir (o producto sin descuento) → confirmación seca'],
  ['06-salida-oferta', '01b-paso1-descuento-aplicado', '«Aplicar mi descuento» → vuelve al paso 1 con precios nuevos', 'vuelve'],
]

